print("")
linea1 = (" ___ |\________/)")
linea18 =(" [_,_]) \ / \|")
linea11 =(" /|=T=|] / __ __\\")
linea13 =(" |\ ' // |_ 9 p ]\\")
linea15 =(" ||'-'/--. / /\\ =| \|\\ \\")
linea16 =(" /|| <\/> |\ | '._, @ @)<_)")
linea21 =(" | |\ | | \.__/(_;_)")
linea31 =(" | . H | | : '='|")
linea6 =(" | | _H__/ _| : |")
linea7 =(" \ '.__ \ / ; ';")
linea19 =(" __'-._(_}==.' : ;")
linea71 =(" (___| /-' | :. :")
linea371 =(" [.-' \ | \ \ ; :")
linea2 =(" .-' | | | | ':")
linea22 =(" / |==| \ \ / \_")
linea661 =(" / [ | '._\_ -._ \\")
linea517 =(" / \__) __.- \ \ )\\")
linea81 =("/ | /.' >>)")
linea61 =("| \ |\ |")
linea414 =("| .' '-. | \ /")
linea651 =("| / / / / /")
linea51 =(" | /")
linea41 =("")
print(linea1)
print(linea18)
print(linea11)
print(linea13)
print(linea15)
print(linea16)
print(linea21)
print(linea31)
print(linea6)
print(linea7)
print(linea19)
print(linea71)
print(linea371)
print(linea2)
print(linea22)
print(linea661)
print(linea517)
print(linea81)
print(linea61)
print(linea414)
print(linea651)
print(linea51)
print(linea41)

#Hay que ordenarlo, siendole sincero profesor lo intente pero fue un dolor de cabeza asi que ocupe el solucionario, ¿de verdad hay gente que los hace a mano? Tienes que amar mucho el arte para esto dios mio.